name: Build Android APK

on:
  push:
    branches:
      - main  # Triggers the build every time you push to the main branch
  workflow_dispatch: # Allows you to manually click a button to build the APK

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust based on your project requirements
          cache: 'gradle'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Generated APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
