- name: Install system packages
  run: |
    sudo apt-get update
    sudo apt-get install -y \
      autoconf \
      automake \
      libtool \
      libltdl-dev \
      pkg-config \
      m4 \
      git \
      zip \
      unzip \
      openjdk-17-jdk \
      python3-pip \
      zlib1g-dev \
      libffi-dev \
      libssl-dev      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
